sqportal/sqportal/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using sqportal.DAL;
using sqportal.Models;
using sqportal.Models.Models;
using sqportal.ServiceLayer;

namespace sqportal.Controllers
{
    [Authorize(Roles = "admin")]
    public class TestController : Controller
    {
        private readonly AccountService _accountService;

         public TestController()
        {
            _accountService = new AccountService(new DataRepository());
        }

        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UserEdit(int id)
        {
            var acc = _accountService.GetEditPersonAccount(id);
            return View(acc);
        }

        
        public ActionResult CreateUser()
        {
            var model = new CreateUserViewModel();
            var allRoles = HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>().Roles;

            var checkBoxListRole = allRoles.Select(role => new RoleModel()
            {
                Name = role.Name,
                Selected = false,
                ID = role.Id
            }).ToList();

            model.Roles = checkBoxListRole;
            return View(model);
        }

        public ActionResult UserList()
        {
            return View(_accountService.GetPersonAccounts());
        }
    }
}

sqportal/sqportal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SQportal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Roles", "Index", "Roles")</li>
                    <li>@Html.ActionLink("API Users List", "../api/useradmindata/userslist")</li>
                    <li>@Html.ActionLink("Users List", "UserList", "Test")</li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.ActionLink("Create User", "CreateUser", "Test")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>